[package]
name = "comdex-bindings"
version = "0.6.0"
authors = ["Comdex"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Comdex blockchain"


[dependencies]
cosmwasm-std = "1.0.0-beta8"
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0-beta8"


[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true